#!/usr/bin/env python

##
## Ralph Bean <ralph.bean@gmail.com>
##
## This software may be freely redistributed under the terms of the GNU
## general public license.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

from func.overlord.inventory_notifier import FuncInventoryNotifier

if __name__ == '__main__':
    notif = FuncInventoryNotifier()
    notif.run()

